// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: proto/protos/room.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{0}
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId      string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UsersLength int32  `protobuf:"varint,3,opt,name=users_length,json=usersLength,proto3" json:"users_length,omitempty"`
	Closed      bool   `protobuf:"varint,4,opt,name=closed,proto3" json:"closed,omitempty"`
	CreatedAt   int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Schaduled   *int64 `protobuf:"varint,6,opt,name=schaduled,proto3,oneof" json:"schaduled,omitempty"`
	RoomExpiry  *int64 `protobuf:"varint,7,opt,name=room_expiry,json=roomExpiry,proto3,oneof" json:"room_expiry,omitempty"`
	ArchivedAt  *int64 `protobuf:"varint,8,opt,name=archived_at,json=archivedAt,proto3,oneof" json:"archived_at,omitempty"`
	ClosedAt    *int64 `protobuf:"varint,9,opt,name=closed_at,json=closedAt,proto3,oneof" json:"closed_at,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{1}
}

func (x *Room) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Room) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Room) GetUsersLength() int32 {
	if x != nil {
		return x.UsersLength
	}
	return 0
}

func (x *Room) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *Room) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Room) GetSchaduled() int64 {
	if x != nil && x.Schaduled != nil {
		return *x.Schaduled
	}
	return 0
}

func (x *Room) GetRoomExpiry() int64 {
	if x != nil && x.RoomExpiry != nil {
		return *x.RoomExpiry
	}
	return 0
}

func (x *Room) GetArchivedAt() int64 {
	if x != nil && x.ArchivedAt != nil {
		return *x.ArchivedAt
	}
	return 0
}

func (x *Room) GetClosedAt() int64 {
	if x != nil && x.ClosedAt != nil {
		return *x.ClosedAt
	}
	return 0
}

type Rooms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*Room `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Total *int32  `protobuf:"varint,2,opt,name=total,proto3,oneof" json:"total,omitempty"`
}

func (x *Rooms) Reset() {
	*x = Rooms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rooms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rooms) ProtoMessage() {}

func (x *Rooms) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rooms.ProtoReflect.Descriptor instead.
func (*Rooms) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{2}
}

func (x *Rooms) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *Rooms) GetTotal() int32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

type RegisterRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	UsersLength int32  `protobuf:"varint,2,opt,name=users_length,json=usersLength,proto3" json:"users_length,omitempty"`
	Scheduled   *int64 `protobuf:"varint,3,opt,name=scheduled,proto3,oneof" json:"scheduled,omitempty"`
	RoomExpiry  *int64 `protobuf:"varint,4,opt,name=room_expiry,json=roomExpiry,proto3,oneof" json:"room_expiry,omitempty"`
}

func (x *RegisterRoomRequest) Reset() {
	*x = RegisterRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRoomRequest) ProtoMessage() {}

func (x *RegisterRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRoomRequest.ProtoReflect.Descriptor instead.
func (*RegisterRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRoomRequest) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *RegisterRoomRequest) GetUsersLength() int32 {
	if x != nil {
		return x.UsersLength
	}
	return 0
}

func (x *RegisterRoomRequest) GetScheduled() int64 {
	if x != nil && x.Scheduled != nil {
		return *x.Scheduled
	}
	return 0
}

func (x *RegisterRoomRequest) GetRoomExpiry() int64 {
	if x != nil && x.RoomExpiry != nil {
		return *x.RoomExpiry
	}
	return 0
}

type RegisterRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *RegisterRoomResponse) Reset() {
	*x = RegisterRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRoomResponse) ProtoMessage() {}

func (x *RegisterRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRoomResponse.ProtoReflect.Descriptor instead.
func (*RegisterRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRoomResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type CloseRoomByRoomIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *CloseRoomByRoomIdRequest) Reset() {
	*x = CloseRoomByRoomIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseRoomByRoomIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRoomByRoomIdRequest) ProtoMessage() {}

func (x *CloseRoomByRoomIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRoomByRoomIdRequest.ProtoReflect.Descriptor instead.
func (*CloseRoomByRoomIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{5}
}

func (x *CloseRoomByRoomIdRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomByUserId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetRoomByUserId) Reset() {
	*x = GetRoomByUserId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomByUserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomByUserId) ProtoMessage() {}

func (x *GetRoomByUserId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomByUserId.ProtoReflect.Descriptor instead.
func (*GetRoomByUserId) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoomByUserId) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRoomByRoomId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *GetRoomByRoomId) Reset() {
	*x = GetRoomByRoomId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomByRoomId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomByRoomId) ProtoMessage() {}

func (x *GetRoomByRoomId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomByRoomId.ProtoReflect.Descriptor instead.
func (*GetRoomByRoomId) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoomByRoomId) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type IsRoomJoinableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *IsRoomJoinableRequest) Reset() {
	*x = IsRoomJoinableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsRoomJoinableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsRoomJoinableRequest) ProtoMessage() {}

func (x *IsRoomJoinableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsRoomJoinableRequest.ProtoReflect.Descriptor instead.
func (*IsRoomJoinableRequest) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{8}
}

func (x *IsRoomJoinableRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *IsRoomJoinableRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsRoomJoinableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *IsRoomJoinableResponse) Reset() {
	*x = IsRoomJoinableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsRoomJoinableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsRoomJoinableResponse) ProtoMessage() {}

func (x *IsRoomJoinableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsRoomJoinableResponse.ProtoReflect.Descriptor instead.
func (*IsRoomJoinableResponse) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{9}
}

func (x *IsRoomJoinableResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Users struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms      []*Room `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	TotalCount *int64  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3,oneof" json:"total_count,omitempty"`
}

func (x *Users) Reset() {
	*x = Users{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{10}
}

func (x *Users) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *Users) GetTotalCount() int64 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

type Pagination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset   int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit    int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	GetTotal bool  `protobuf:"varint,3,opt,name=get_total,json=getTotal,proto3" json:"get_total,omitempty"`
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{11}
}

func (x *Pagination) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetGetTotal() bool {
	if x != nil {
		return x.GetTotal
	}
	return false
}

type RoomLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEvent string `protobuf:"bytes,3,opt,name=user_event,json=userEvent,proto3" json:"user_event,omitempty"`
	CreatedAt int64  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *RoomLog) Reset() {
	*x = RoomLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLog) ProtoMessage() {}

func (x *RoomLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLog.ProtoReflect.Descriptor instead.
func (*RoomLog) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{12}
}

func (x *RoomLog) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomLog) GetUserEvent() string {
	if x != nil {
		return x.UserEvent
	}
	return ""
}

func (x *RoomLog) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type AddRoomLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEvent string `protobuf:"bytes,3,opt,name=user_event,json=userEvent,proto3" json:"user_event,omitempty"`
}

func (x *AddRoomLog) Reset() {
	*x = AddRoomLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRoomLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomLog) ProtoMessage() {}

func (x *AddRoomLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomLog.ProtoReflect.Descriptor instead.
func (*AddRoomLog) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{13}
}

func (x *AddRoomLog) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AddRoomLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddRoomLog) GetUserEvent() string {
	if x != nil {
		return x.UserEvent
	}
	return ""
}

type RoomLogs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomLogs []*RoomLog `protobuf:"bytes,1,rep,name=room_logs,json=roomLogs,proto3" json:"room_logs,omitempty"`
	Total    *int32     `protobuf:"varint,2,opt,name=total,proto3,oneof" json:"total,omitempty"`
}

func (x *RoomLogs) Reset() {
	*x = RoomLogs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLogs) ProtoMessage() {}

func (x *RoomLogs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLogs.ProtoReflect.Descriptor instead.
func (*RoomLogs) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{14}
}

func (x *RoomLogs) GetRoomLogs() []*RoomLog {
	if x != nil {
		return x.RoomLogs
	}
	return nil
}

func (x *RoomLogs) GetTotal() int32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

type AddRoomResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Approvers []string `protobuf:"bytes,2,rep,name=approvers,proto3" json:"approvers,omitempty"`
	Deniers   []string `protobuf:"bytes,3,rep,name=Deniers,proto3" json:"Deniers,omitempty"`
}

func (x *AddRoomResult) Reset() {
	*x = AddRoomResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRoomResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomResult) ProtoMessage() {}

func (x *AddRoomResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomResult.ProtoReflect.Descriptor instead.
func (*AddRoomResult) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{15}
}

func (x *AddRoomResult) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AddRoomResult) GetApprovers() []string {
	if x != nil {
		return x.Approvers
	}
	return nil
}

func (x *AddRoomResult) GetDeniers() []string {
	if x != nil {
		return x.Deniers
	}
	return nil
}

type RoomResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Approvers []string `protobuf:"bytes,2,rep,name=approvers,proto3" json:"approvers,omitempty"`
	Deniers   []string `protobuf:"bytes,3,rep,name=Deniers,proto3" json:"Deniers,omitempty"`
	CreatedAt int64    `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *RoomResult) Reset() {
	*x = RoomResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResult) ProtoMessage() {}

func (x *RoomResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResult.ProtoReflect.Descriptor instead.
func (*RoomResult) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{16}
}

func (x *RoomResult) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomResult) GetApprovers() []string {
	if x != nil {
		return x.Approvers
	}
	return nil
}

func (x *RoomResult) GetDeniers() []string {
	if x != nil {
		return x.Deniers
	}
	return nil
}

func (x *RoomResult) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type RoomResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomResults []*RoomResult `protobuf:"bytes,1,rep,name=room_results,json=roomResults,proto3" json:"room_results,omitempty"`
	Total       *int32        `protobuf:"varint,2,opt,name=total,proto3,oneof" json:"total,omitempty"`
}

func (x *RoomResults) Reset() {
	*x = RoomResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResults) ProtoMessage() {}

func (x *RoomResults) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResults.ProtoReflect.Descriptor instead.
func (*RoomResults) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{17}
}

func (x *RoomResults) GetRoomResults() []*RoomResult {
	if x != nil {
		return x.RoomResults
	}
	return nil
}

func (x *RoomResults) GetTotal() int32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

type RoomResultsCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success int32 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Failed  int32 `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
}

func (x *RoomResultsCount) Reset() {
	*x = RoomResultsCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomResultsCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResultsCount) ProtoMessage() {}

func (x *RoomResultsCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResultsCount.ProtoReflect.Descriptor instead.
func (*RoomResultsCount) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{18}
}

func (x *RoomResultsCount) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *RoomResultsCount) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

type RoomUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId          string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status          string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FirstOccurrence int64  `protobuf:"varint,3,opt,name=first_occurrence,json=firstOccurrence,proto3" json:"first_occurrence,omitempty"`
}

func (x *RoomUser) Reset() {
	*x = RoomUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomUser) ProtoMessage() {}

func (x *RoomUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomUser.ProtoReflect.Descriptor instead.
func (*RoomUser) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{19}
}

func (x *RoomUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomUser) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RoomUser) GetFirstOccurrence() int64 {
	if x != nil {
		return x.FirstOccurrence
	}
	return 0
}

type RoomUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomUsers []*RoomUser `protobuf:"bytes,1,rep,name=room_users,json=roomUsers,proto3" json:"room_users,omitempty"`
	Total     *int32      `protobuf:"varint,2,opt,name=total,proto3,oneof" json:"total,omitempty"`
}

func (x *RoomUsers) Reset() {
	*x = RoomUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protos_room_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomUsers) ProtoMessage() {}

func (x *RoomUsers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protos_room_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomUsers.ProtoReflect.Descriptor instead.
func (*RoomUsers) Descriptor() ([]byte, []int) {
	return file_proto_protos_room_proto_rawDescGZIP(), []int{20}
}

func (x *RoomUsers) GetRoomUsers() []*RoomUser {
	if x != nil {
		return x.RoomUsers
	}
	return nil
}

func (x *RoomUsers) GetTotal() int32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

var File_proto_protos_room_proto protoreflect.FileDescriptor

var file_proto_protos_room_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72,
	0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xdf, 0x02, 0x0a, 0x04, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x21, 0x0a,
	0x09, 0x73, 0x63, 0x68, 0x61, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x00, 0x52, 0x09, 0x73, 0x63, 0x68, 0x61, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x24, 0x0a, 0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x79, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x48, 0x02, 0x52, 0x0a, 0x61,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x41, 0x74, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x48,
	0x03, 0x52, 0x08, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x41, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0c,
	0x0a, 0x0a, 0x5f, 0x73, 0x63, 0x68, 0x61, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x42, 0x0e, 0x0a, 0x0c,
	0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x42, 0x0e, 0x0a, 0x0c,
	0x5f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x42, 0x0c, 0x0a, 0x0a,
	0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x22, 0x4e, 0x0a, 0x05, 0x52, 0x6f,
	0x6f, 0x6d, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05,
	0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x88, 0x01, 0x01,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0xb9, 0x01, 0x0a, 0x13, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x0c,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12,
	0x21, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x00, 0x52, 0x09, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x45,
	0x78, 0x70, 0x69, 0x72, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x22, 0x2a, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69,
	0x6e, 0x6b, 0x22, 0x33, 0x0a, 0x18, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x42,
	0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x79,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22,
	0x49, 0x0a, 0x15, 0x49, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x4a, 0x6f, 0x69, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x16, 0x49, 0x73,
	0x52, 0x6f, 0x6f, 0x6d, 0x4a, 0x6f, 0x69, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5f, 0x0a, 0x05,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x24, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0a,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a,
	0x0c, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x57, 0x0a,
	0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x65, 0x74,
	0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x67, 0x65,
	0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x79, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x6f,
	0x67, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x5d, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x6f, 0x67, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0x5b, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x2a, 0x0a, 0x09,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x6f, 0x67, 0x52, 0x08,
	0x72, 0x6f, 0x6f, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x60, 0x0a,
	0x0d, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x6e, 0x69, 0x65, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x44, 0x65, 0x6e, 0x69, 0x65, 0x72, 0x73, 0x22,
	0x7c, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x6e, 0x69, 0x65, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x44, 0x65, 0x6e, 0x69, 0x65, 0x72, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x67, 0x0a,
	0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x33, 0x0a, 0x0c,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x44, 0x0a, 0x10, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x22, 0x66, 0x0a, 0x08,
	0x52, 0x6f, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x5f, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4f, 0x63, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x22, 0x5f, 0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x12, 0x2d, 0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x12, 0x19, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x00, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0xc0, 0x08, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x19, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a,
	0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x1e, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x79, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x39, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x5f,
	0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x5f, 0x62, 0x79, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12,
	0x15, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x0b, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f,
	0x6f, 0x6d, 0x73, 0x12, 0x37, 0x0a, 0x12, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x62, 0x79, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12, 0x15, 0x2e, 0x72, 0x6f, 0x6f, 0x6d,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x1a, 0x0a, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x3c, 0x0a, 0x17,
	0x67, 0x65, 0x74, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x62, 0x79,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x15, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x0a,
	0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x4a, 0x0a, 0x1a, 0x67, 0x65,
	0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x62,
	0x79, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12, 0x15, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x1a,
	0x15, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x50, 0x0a, 0x13, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1b, 0x2e,
	0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x49, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x4a, 0x6f, 0x69, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x72, 0x6f, 0x6f,
	0x6d, 0x2e, 0x49, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x4a, 0x6f, 0x69, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x5f,
	0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x10, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0b, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x2f, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x5f, 0x6f, 0x70, 0x65, 0x6e,
	0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x10, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0b, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x2d, 0x0a, 0x0c, 0x61, 0x64, 0x64, 0x5f, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x6c, 0x6f, 0x67, 0x12, 0x10, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x41, 0x64, 0x64,
	0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x6f, 0x67, 0x1a, 0x0b, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x40, 0x0a, 0x17, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x6c, 0x6f, 0x67, 0x73, 0x5f, 0x62, 0x79, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12,
	0x15, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x79,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x1a, 0x0e, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f,
	0x6f, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x33, 0x0a, 0x0f, 0x61, 0x64, 0x64, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x13, 0x2e, 0x72, 0x6f, 0x6f, 0x6d,
	0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x0b,
	0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x37, 0x0a, 0x10, 0x67,
	0x65, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12,
	0x10, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x11, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x12, 0x44, 0x0a, 0x19, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x62, 0x79, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x69,
	0x64, 0x12, 0x15, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x42, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x1a, 0x10, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3d, 0x0a, 0x16, 0x67, 0x65,
	0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0b, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x16, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x0d, 0x67, 0x65, 0x74,
	0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x10, 0x2e, 0x72, 0x6f, 0x6f,
	0x6d, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0f, 0x2e, 0x72,
	0x6f, 0x6f, 0x6d, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x32, 0x0a,
	0x0c, 0x61, 0x64, 0x64, 0x5f, 0x62, 0x61, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x12, 0x15, 0x2e,
	0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x1a, 0x0b, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x35, 0x0a, 0x0f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x62, 0x61, 0x6e, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x0b, 0x2e, 0x72, 0x6f,
	0x6f, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_protos_room_proto_rawDescOnce sync.Once
	file_proto_protos_room_proto_rawDescData = file_proto_protos_room_proto_rawDesc
)

func file_proto_protos_room_proto_rawDescGZIP() []byte {
	file_proto_protos_room_proto_rawDescOnce.Do(func() {
		file_proto_protos_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_protos_room_proto_rawDescData)
	})
	return file_proto_protos_room_proto_rawDescData
}

var file_proto_protos_room_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_protos_room_proto_goTypes = []interface{}{
	(*Empty)(nil),                    // 0: room.Empty
	(*Room)(nil),                     // 1: room.Room
	(*Rooms)(nil),                    // 2: room.Rooms
	(*RegisterRoomRequest)(nil),      // 3: room.RegisterRoomRequest
	(*RegisterRoomResponse)(nil),     // 4: room.RegisterRoomResponse
	(*CloseRoomByRoomIdRequest)(nil), // 5: room.CloseRoomByRoomIdRequest
	(*GetRoomByUserId)(nil),          // 6: room.GetRoomByUserId
	(*GetRoomByRoomId)(nil),          // 7: room.GetRoomByRoomId
	(*IsRoomJoinableRequest)(nil),    // 8: room.IsRoomJoinableRequest
	(*IsRoomJoinableResponse)(nil),   // 9: room.IsRoomJoinableResponse
	(*Users)(nil),                    // 10: room.Users
	(*Pagination)(nil),               // 11: room.Pagination
	(*RoomLog)(nil),                  // 12: room.RoomLog
	(*AddRoomLog)(nil),               // 13: room.AddRoomLog
	(*RoomLogs)(nil),                 // 14: room.RoomLogs
	(*AddRoomResult)(nil),            // 15: room.AddRoomResult
	(*RoomResult)(nil),               // 16: room.RoomResult
	(*RoomResults)(nil),              // 17: room.RoomResults
	(*RoomResultsCount)(nil),         // 18: room.RoomResultsCount
	(*RoomUser)(nil),                 // 19: room.RoomUser
	(*RoomUsers)(nil),                // 20: room.RoomUsers
}
var file_proto_protos_room_proto_depIdxs = []int32{
	1,  // 0: room.Rooms.rooms:type_name -> room.Room
	1,  // 1: room.Users.rooms:type_name -> room.Room
	12, // 2: room.RoomLogs.room_logs:type_name -> room.RoomLog
	16, // 3: room.RoomResults.room_results:type_name -> room.RoomResult
	19, // 4: room.RoomUsers.room_users:type_name -> room.RoomUser
	3,  // 5: room.RoomService.register_room:input_type -> room.RegisterRoomRequest
	5,  // 6: room.RoomService.close_room:input_type -> room.CloseRoomByRoomIdRequest
	6,  // 7: room.RoomService.get_rooms_by_userid:input_type -> room.GetRoomByUserId
	7,  // 8: room.RoomService.get_room_by_roomid:input_type -> room.GetRoomByRoomId
	6,  // 9: room.RoomService.get_open_room_by_userid:input_type -> room.GetRoomByUserId
	7,  // 10: room.RoomService.get_room_creator_by_roomid:input_type -> room.GetRoomByRoomId
	8,  // 11: room.RoomService.check_room_joinable:input_type -> room.IsRoomJoinableRequest
	11, // 12: room.RoomService.get_rooms:input_type -> room.Pagination
	11, // 13: room.RoomService.get_open_rooms:input_type -> room.Pagination
	13, // 14: room.RoomService.add_room_log:input_type -> room.AddRoomLog
	7,  // 15: room.RoomService.get_room_logs_by_roomid:input_type -> room.GetRoomByRoomId
	15, // 16: room.RoomService.add_room_result:input_type -> room.AddRoomResult
	11, // 17: room.RoomService.get_room_results:input_type -> room.Pagination
	7,  // 18: room.RoomService.get_room_result_by_roomid:input_type -> room.GetRoomByRoomId
	0,  // 19: room.RoomService.get_room_results_count:input_type -> room.Empty
	11, // 20: room.RoomService.get_all_users:input_type -> room.Pagination
	6,  // 21: room.RoomService.add_ban_user:input_type -> room.GetRoomByUserId
	6,  // 22: room.RoomService.remove_ban_user:input_type -> room.GetRoomByUserId
	4,  // 23: room.RoomService.register_room:output_type -> room.RegisterRoomResponse
	0,  // 24: room.RoomService.close_room:output_type -> room.Empty
	2,  // 25: room.RoomService.get_rooms_by_userid:output_type -> room.Rooms
	1,  // 26: room.RoomService.get_room_by_roomid:output_type -> room.Room
	1,  // 27: room.RoomService.get_open_room_by_userid:output_type -> room.Room
	6,  // 28: room.RoomService.get_room_creator_by_roomid:output_type -> room.GetRoomByUserId
	9,  // 29: room.RoomService.check_room_joinable:output_type -> room.IsRoomJoinableResponse
	2,  // 30: room.RoomService.get_rooms:output_type -> room.Rooms
	2,  // 31: room.RoomService.get_open_rooms:output_type -> room.Rooms
	0,  // 32: room.RoomService.add_room_log:output_type -> room.Empty
	14, // 33: room.RoomService.get_room_logs_by_roomid:output_type -> room.RoomLogs
	0,  // 34: room.RoomService.add_room_result:output_type -> room.Empty
	17, // 35: room.RoomService.get_room_results:output_type -> room.RoomResults
	16, // 36: room.RoomService.get_room_result_by_roomid:output_type -> room.RoomResult
	18, // 37: room.RoomService.get_room_results_count:output_type -> room.RoomResultsCount
	20, // 38: room.RoomService.get_all_users:output_type -> room.RoomUsers
	0,  // 39: room.RoomService.add_ban_user:output_type -> room.Empty
	0,  // 40: room.RoomService.remove_ban_user:output_type -> room.Empty
	23, // [23:41] is the sub-list for method output_type
	5,  // [5:23] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_protos_room_proto_init() }
func file_proto_protos_room_proto_init() {
	if File_proto_protos_room_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_protos_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rooms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseRoomByRoomIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomByUserId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomByRoomId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsRoomJoinableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsRoomJoinableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Users); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pagination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRoomLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomLogs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRoomResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomResultsCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protos_room_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_protos_room_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_proto_protos_room_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_proto_protos_room_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_proto_protos_room_proto_msgTypes[10].OneofWrappers = []interface{}{}
	file_proto_protos_room_proto_msgTypes[14].OneofWrappers = []interface{}{}
	file_proto_protos_room_proto_msgTypes[17].OneofWrappers = []interface{}{}
	file_proto_protos_room_proto_msgTypes[20].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_protos_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_protos_room_proto_goTypes,
		DependencyIndexes: file_proto_protos_room_proto_depIdxs,
		MessageInfos:      file_proto_protos_room_proto_msgTypes,
	}.Build()
	File_proto_protos_room_proto = out.File
	file_proto_protos_room_proto_rawDesc = nil
	file_proto_protos_room_proto_goTypes = nil
	file_proto_protos_room_proto_depIdxs = nil
}
